db:
  image: kartoza/postgis:9.4-2.1
  #volumes:
    #- ./pg/postgres_data:/var/lib/postgresql
  environment:
    - USERNAME=docker
    - PASS=docker

qgisserver:
  build : 2.18
  #image: kartoza/qgis-server
  hostname: qgis-server
  volumes:
    - ./gis:/gis
  links:
    - db:db


nginx:
  image: nginx
  hostname: nginx
  volumes:
    - ./nginx-conf:/etc/nginx/conf.d
  ports:
    - "0.0.0.0:8080:80"
  links:
    - qgisserver:qgisserver


